spring:
  webflux:
    hiddenmethod:
      filter:
        enabled: true
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  thymeleaf:
    cache: false
